sudo: required
services:
  - docker

before_install:
  - docker build -t wilmer737/docker-react -f Dockerfile.dev .

script:
  - docker run wilmer737/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-west-1-734994193264"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
